name: my_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  url_launcher: ^6.1.2

  walletconnect_dart: ^0.0.10

  google_fonts: ^3.0.1

  slider_button: ^2.0.0

  web3dart: ^2.3.5

  qr_flutter: ^4.0.0

  qr_code_scanner: ^1.0.0

  flutter_dotenv: ^5.0.2

  http: ^0.13.4

  dropdown_search: ^5.0.2

  lottie: ^1.4.1

  # Push notification
  firebase_messaging: ^14.1.4

  # Enable firebase services
  firebase_core: ^2.4.0

  # To control showing notifications and create notification channels.
  flutter_local_notifications: ^9.5.1

  flutter_launcher_icons: ^0.10.0

  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/CryptoPayementLogo.png"


flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - .env
    - assets/images/
    - assets/blockchain/chainlinkAggregatorAbi.json
    - assets/blockchain/erc20TokenContractABI.json
    - smartcontracts/contracts/UPIToAddress.sol
    - assets/lottie/success.json
    - assets/lottie/timeout.json
    - assets/lottie/transactionfailed.json
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
